INSERT INTO DEPARTMENTS(
    DEPARTMENT_ID,
    DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
)
VALUES (70, 'Public Relations', 100, 1700);
/
INSERT INTO DEPARTMENTS
VALUES (80, 'Public Relations2', 111, 1700);
/
INSERT INTO EMPLOYEES(
    EMPLOYEE_ID, 
    FIRST_NAME,
    LAST_NAME,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    MANAGER_ID,
    DEPARTMENT_ID
)
VALUES (
    113,
    'Luis',
    'Popp',
    '515.124.4567',
    CURRENT_DATE,
    'FI_ACCOUNT',
    6900,
    110,
    100
);
/
INSERT INTO EMPLOYEES
VALUES (114, 'Den', 'Raphealy');
/
DELETE EMPLOYEES
WHERE SALARY = 2600;
/
SELECT * FROM EMPLOYEES
WHERE SALARY = 2600;
/
SELECT * FROM EMPLOYEES ORDER BY SALARY ASC;
SELECT EMPLOYEES_SEQ.CURRVAL FROM DUAL;