Select * FROM JOBS;
/
DESCRIBE jobs
/
select DEPARTMENT_ID, DEPARTMENT_NAME
from Departments;
/
SELECT LAST_NAME, LAST_NAME || q'[ algo's ]'  || FIRST_NAME as "Nombre Completo", SALARY, 12*SALARY "Salario Anual"
FROM EMPLOYEES;
/
SELECT LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT, SALARY * NVL (COMMISSION_PCT,0) /* NVL : NULL VALUE */
FROM EMPLOYEES;
/
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;
/
DESCRIBE EMPLOYEES

-- PRACTICAS 3
/
SELECT Salary, FIRST_NAME || ' ' || LAST_NAME nombre
FROM EMPLOYEES 
WHERE SALARY BETWEEN 2500 AND 3500
order by 2;
/
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME BETWEEN 'King' AND 'Whalen'
/
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME = 'King'
/
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%';
/
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%';
/
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE LAST_NAME like '%' ESCAPE '^';
/
SELECT LAST_NAME, Manager_id
FROM EMPLOYEES
WHERE MANAGER_ID = null;
/
SELECT * FROM EMPLOYEES
WHERE (MANAGER_ID is null and COMMISSION_PCT is null) or (MANAGER_ID = COMMISSION_PCT);
/
SELECT LAST_NAME, DEPARTMENT_ID, Salary
FROM EMPLOYEES
WHERE(DEPARTMENT_ID = 60 OR DEPARTMENT_ID = 80) AND SALARY>10000;