Select * FROM JOBS;
/
DESCRIBE jobs
/
select DEPARTMENT_ID, DEPARTMENT_NAME
from Departments;
/
SELECT LAST_NAME, LAST_NAME || q'[ algo's ]'  || FIRST_NAME as "Nombre Completo", SALARY, 12*SALARY "Salario Anual"
FROM EMPLOYEES;
/
SELECT LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT, SALARY * NVL (COMMISSION_PCT,0) /* NVL : NULL VALUE */
FROM EMPLOYEES;
/
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;