-- 3.1
/
SELECT LAST_NAME, Salary 
FROM EMPLOYEES
WHERE SALARY > 12000;
/
-- 3.2
/
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;
/
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 12000;
/
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE (LAST_NAME = 'Matos') or LAST_NAME = 'Taylor';
/
-- 3.5
/
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20 OR DEPARTMENT_ID =50
order by LAST_NAME;
-- 3.6
/
SELECT LAST_NAME as Employee, SALARY as "Month Salary"
FROM EMPLOYEES
WHERE (DEPARTMENT_ID = 20 or DEPARTMENT_ID = 50) AND (SALARY BETWEEN 5000 AND 12000);
--3.7
/
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE '01-JAN-06' <= HIRE_DATE AND HIRE_DATE < '01-JAN-07';
--3.8
/
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID is null;
--3.9
/
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY 2 DESC, 3 DESC;
--3.10
/
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY,