--9.1
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK';
/
--9.2
SELECT COUNTRY_ID, COUNTRY_NAME
FROM COUNTRIES
MINUS
SELECT DISTINCT C.COUNTRY_ID, C.COUNTRY_NAME
FROM COUNTRIES C
JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
ORDER BY COUNTRY_ID;
/
--9.3
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 50
UNION
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 80;
/
--9,4
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
INTERSECT
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP';
/
--9.5
SELECT LAST_NAME, DEPARTMENT_ID, NULL AS DEPARTMENT_NAME
FROM EMPLOYEES
UNION --UNION ALL solo si no quiero que cuente los repetidos
SELECT NULL AS LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS
ORDER BY DEPARTMENT_ID, DEPARTMENT_NAME;


