--7.1
SELECT L.LOCATION_ID, 
       L.STREET_ADDRESS, 
       L.CITY, 
       L.STATE_PROVINCE, 
       C.COUNTRY_NAME
FROM LOCATIONS L
NATURAL JOIN COUNTRIES C;
/
--7.2
SELECT E.LAST_NAME,
       E.DEPARTMENT_ID,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY E.LAST_NAME;
/
--7.3
SELECT E.LAST_NAME,
       E.JOB_ID,
       E.DEPARTMENT_ID,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY = 'Toronto';
/
--7.4
SELECT E.LAST_NAME "Employee",
       E.MANAGER_ID "Emp#",
       M.LAST_NAME "Manager",
       M.MANAGER_ID "Mgr#"
FROM EMPLOYEES E
JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY E.LAST_NAME;
/
--7.5
SELECT E.LAST_NAME "Employee",
       E.MANAGER_ID "Emp#",
       M.LAST_NAME "Manager",
       M.MANAGER_ID "Mgr#"
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY E.LAST_NAME;
/
--7.6
SELECT E1.LAST_NAME "EMPLOYEE",
       E1.DEPARTMENT_ID "DEPARTMENT",
       E2.LAST_NAME AS "COLLEAGUE"
FROM EMPLOYEES E1
JOIN EMPLOYEES E2 ON E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
ORDER BY E1.DEPARTMENT_ID, E1.LAST_NAME, E2.LAST_NAME;
/
--7.7
DESCRIBE JOB_GRADES
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME,
       E.JOB_ID,
       E.SALARY,
       J.GRADE
FROM EMPLOYEES E 
JOIN JOB_GRADES J ON E.SALARY BETWEEN J.HIGHEST_SAL AND J.LOWEST_SAL
ORDER BY E.LAST_NAME;
/
--7.8
SELECT FIRST_NAME || ' ' || LAST_NAME,
       HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > (
    SELECT HIRE_DATE
    FROM EMPLOYEES
    WHERE LAST_NAME = 'Davies'
)
ORDER BY HIRE_DATE;
/
--7.9
SELECT E.LAST_NAME,
       E.HIRE_DATE,
       M.LAST_NAME,
       M.HIRE_DATE
FROM EMPLOYEES E 
JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.HIRE_DATE < M.HIRE_DATE
ORDER BY E.HIRE_DATE;


