--6.1
--true
--6.2
--true
--6.3
--true
--6.4
SELECT MAX(SALARY), MIN(SALARY), 
       SUM(SALARY),AVG(SALARY)
FROM EMPLOYEES;
/
--6.5
SELECT JOB_ID, MAX(SALARY), MIN(SALARY), 
       SUM(SALARY),AVG(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;
/
--6.6
SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
WHERE JOB_ID = '&job_id'
GROUP BY JOB_ID;
UNDEFINE job_id
/
--6.7
SELECT COUNT(MANAGER_ID) "Number of Managers"
FROM EMPLOYEES;
/
--6.8
SELECT 
       MAX(SALARY) - MIN (SALARY) DIFFERENCE
FROM EMPLOYEES;
/
--6.9
SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID is not NULL
GROUP BY MANAGER_ID
HAVING MIN(SALARY)>6000
ORDER BY MIN(SALARY) Desc;
/
--6.10
SELECT COUNT(*) TOTAL,
       SUM(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2009 THEN 1 ELSE 0 END)  "2009",
       SUM(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2010 THEN 1 ELSE 0 END)  "2010",
       SUM(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2011 THEN 1 ELSE 0 END)  "2011",
       SUM(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = 2012 THEN 1 ELSE 0 END)  "2012"
FROM EMPLOYEES;
/
--6.11
SELECT JOB_ID,
       SUM(CASE WHEN DEPARTMENT_ID = 20 THEN SALARY ELSE 0 END) "Dept 20",
       SUM(CASE WHEN DEPARTMENT_ID = 50 THEN SALARY ELSE 0 END) "Dept 50",
       SUM(CASE WHEN DEPARTMENT_ID = 80 THEN SALARY ELSE 0 END) "Dept 80",
       SUM(CASE WHEN DEPARTMENT_ID = 20 THEN SALARY ELSE 0 END) "Dept 90",
       SUM(SALARY) "Total"
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN(20,50,80,90)
GROUP BY JOB_ID
ORDER BY JOB_ID;
