--8.1
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME = '&last_name')
AND last_name != '&&last_name';
/
--8.2
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, (SELECT AVG(SALARY) FROM EMPLOYEES) MEDIA
FROM EMPLOYEES
WHERE SALARY >(
    SELECT AVG(SALARY)
    FROM EMPLOYEES
)
ORDER BY SALARY ASC;
/
--8.3
SELECT EMPLOYEE_ID, LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LOWER(LAST_NAME) LIKE ('%u%')
);
/
--8.4
SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM LOCATIONS
    WHERE LOCATION_ID = 1700
);
/
--8.5
SELECT LAST_NAME, SALARY
FROM EMPLOYEES 
WHERE MANAGER_ID IN (
    SELECT EMPLOYEE_ID
    FROM EMPLOYEES
    WHERE LAST_NAME = 'King'
);
/
--8.6
SELECT DEPARTMENT_ID, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
    HAVING COUNT(*) = 1    
);
/
--8.7
SELECT LAST_NAME
FROM EMPLOYEES
WHERE SALARY > ANY (
    SELECT MAX(salary) 
    FROM employees 
    WHERE department_id = 60);
/
--8.8
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, (SELECT AVG(SALARY) FROM EMPLOYEES) M
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE LOWER('%u%')) AND SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);
